### ISSUE TITLE
Website not showing content correctly.

### ISSUE THREAD

**Issue by Khichi13** [Khichi13/khichi13.github.io#1]
@saifkhichi96,
The Slytherin logo you added is not showing. Also, the words 'My Gigs' and 'Blog Posts' are not shown in bold, instead '##' appears before them. Please note I'm getting these issues both on my laptop and mobile phone.

**Comment by saifkhichi96** [comment]
I am working on it. Check back in 10 minutes.

**Comment by saifkhichi96** [comment]
I fixed it.
